//
// Generated file, do not edit! Created by nedtool 5.6 from VoicePacket.msg.
//

#ifndef __VOICEPACKET_M_H
#define __VOICEPACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>VoicePacket.msg:16</tt> by nedtool.
 * <pre>
 * message VoicePacket
 * {
 *     int source_id;
 *     int destination_id;
 * 
 *     double generation_time;
 *     double delayBound;
 *     int packet_size;
 * 
 *     double delay;
 * }
 * </pre>
 */
class VoicePacket : public ::omnetpp::cMessage
{
  protected:
    int source_id;
    int destination_id;
    double generation_time;
    double delayBound;
    int packet_size;
    double delay;

  private:
    void copy(const VoicePacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const VoicePacket&);

  public:
    VoicePacket(const char *name=nullptr, short kind=0);
    VoicePacket(const VoicePacket& other);
    virtual ~VoicePacket();
    VoicePacket& operator=(const VoicePacket& other);
    virtual VoicePacket *dup() const override {return new VoicePacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource_id() const;
    virtual void setSource_id(int source_id);
    virtual int getDestination_id() const;
    virtual void setDestination_id(int destination_id);
    virtual double getGeneration_time() const;
    virtual void setGeneration_time(double generation_time);
    virtual double getDelayBound() const;
    virtual void setDelayBound(double delayBound);
    virtual int getPacket_size() const;
    virtual void setPacket_size(int packet_size);
    virtual double getDelay() const;
    virtual void setDelay(double delay);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const VoicePacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, VoicePacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef __VOICEPACKET_M_H

